config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  defaults export: true do
    devise_for :users

    root "home#index"

    resources :games, only: %i[index show create update destroy] do
      resource :players, only: %i[create destroy]
      resource :turn, only: :create
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  DEFAULT_DECK = [
    *(1..9).flat_map do |n|
      Card::COLORS.flat_map do |c|
        Card.new(color: c, face: n)
      end
    end,
    *Card::COLORS.flat_map do |c|
      [
       Card.new(color: c, face: "0"),
        *2.times.flat_map do
          [
            Card.new(color: c, face: "skip"),
            Card.new(color: c, face: "reverse"),
            Card.new(color: c, face: "plus", plus: 2)
          ]
        end
      ]
    end,
    *4.times.flat_map do
      [
        Card.new(color: "wild", face: "plus", plus: 4),
        Card.new(color: "wild", face: "wild")
      ]
    end
  ].freeze

  enum :status, {
    lobby: 0,
    playing: 1,
    finished: 2,
    abandoned: 3
  }

  has_many :players, dependent: :destroy
  has_many :users, through: :players
  belongs_to :winner, class_name: "User", optional: true
  belongs_to :user

  validates :winner, presence: true, if: :finished?
  validate :enough_players, if: :playing?

  attribute :deck, Card.to_array_type
  attribute :discard, Card.to_array_type

  enum :color, Card.colors.keys

  before_create :shuffle_deck

  after_create :broadcast_to_lobby
  after_update :broadcast

  def start!
    deal
    playing!
  end

  def top
    discard.first
  end

  def place?(card)
    top.place?(card, plus > 0, color)
  end

  def draw
    card = deck.shift
    if deck.empty?
      top_discard = discard.slice!(0, 1)
      self.deck = discard.shuffle
      deck.each do |card|
        card.color = "wild" if card.wild?
      end
    end
    card
  end

  def current_player
    players.order(created_at: :asc)[player_index]
  end

  def last_player
    return nil if last_player_index.nil?

    players.order(created_at: :asc)[last_player_index]
  end

  def player_index_of(player)
    players.order(created_at: :asc).index(player)
  end

  def next_player
    self.player_index = (self.player_index + self.dir) % players.length
  end

  def reverse
    self.dir *= -1
  end

  def user_stream(user)
    "game_#{id}_#{user.id}"
  end

  def player_stream(player)
    user_stream(player.user)
  end

  def broadcast(*other_users)
    if abandoned?
      LobbyChannel.broadcast_to(Game, { type: "destroy", id: })
    else
      LobbyChannel.broadcast_to(Game, { type: "update", game: lobby_data })
    end
    players.each do
      ActionCable.server.broadcast(player_stream(it), player_data(it))
    end
    other_users.each do
      ActionCable.server.broadcast(user_stream(it), user_data(it))
    end
  end

  def broadcast_to_lobby
    LobbyChannel.broadcast_to(Game, { type: "create", game: lobby_data })
  end

  def lobby_data
    { id:, player_count: players.count }
  end

  def user_data(player_user)
    player_data(players.find_by(user: player_user))
  end

  def player_data(player)
    data = {
      id:, status:,
      user: user.email,
      joined: players.include?(player),
      yours: player&.user == user
    }

    case status
    when 'lobby'
      data.merge!(
        players: players
          .order(created_at: :asc)
          .map { { id: it.id, name: it.user.email } }
      )
    when 'playing'
      your_turn = player == current_player
      can_draw = your_turn && (plus > 0 || player.cards.all?{ !place?(it) })
      data.merge!(
        deck_size: deck.count,
        discard_size: discard.count,
        top: top.as_json,
        cards: player.cards.map { it.as_json.merge(place: your_turn && place?(it)) },
        plus:, color:, dir:, can_draw:, your_turn:,
        runo: player.runo?,
        players: players.order(created_at: :asc)
          .reject { it == player }
          .map { {
            id: it.id,
            name: it.user.email,
            card_count: it.cards.count,
            current: it == current_player,
            runo: it.runo?
          } }
      )
    when 'finished'
      data[:winner] = winner == player ? 'you' : winner.user.email
    end

    data.deep_transform_keys { it.to_s.camelize(:lower) }
  end

  private

    def enough_players
      errors.add(:players, :blank) if players.count < 2
    end

    def shuffle_deck
      self.deck = DEFAULT_DECK.dup.shuffle
    end

    def deal
      7.times do
        players.each do |player|
          player.cards << draw
        end
      end
      players.each(&:save!)
      discard.unshift(deck.shift)
      discard.unshift(deck.shift) while discard.first.wild?
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show update destroy]
  before_action :authenticate_user!

  def index
    render json: {
      your_games: current_user.games.playing.map(&:lobby_data),
      games: Game.lobby.map(&:lobby_data)
    }
  end

  # GET /games/1 or /games/1.json
  def show
    @user_data = @game.user_data(current_user)

    respond_to do |format|
      format.html { render inertia: "Game", props: { game: @user_data } }
      format.json { render json: @user_data }
    end
  end

  # POST /games or /games.json
  def create
    @game = Game.create(user: current_user)
    @game.players << Player.new(user: current_user)

    render json: @game.user_data(current_user)
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.abandoned!

    head :no_content
  end

  def update
    @game.start! if @game.lobby? && @game.players.length >= 2

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params.expect(:id))
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game.html.erb
<% last_play = local_assigns[:last_play] ? game.last_play.merge(player: game.last_player).symbolize_keys : {}  %>
<% current_user_player = game.players.find_by(user: current_user) %>

<div id="<%= dom_id game %>" data-controller="game">
  <h1><%= game.user.email %>'s game</h1>

  <% case game.status %>
  <% when "lobby" %>
    <% if game.players.length < 2 %>
      <h2>Waiting for players...</h2>
    <% else %>
      <h2>Ready to start!</h2>
      <% if game.user == current_user %>
        <%= button_to 'Start!', game, method: :patch %>
      <% end %>
    <% end %>

    <ul>
      <% game.players.each do |player| %>
        <li><%= player.user.email %></li>
      <% end %>
    </ul>

    <% if game.users.include?(current_user) %>
      <% if game.user != current_user %>
        <%= button_to 'Leave', game_players_path(game), method: :delete %>
      <% end %>
    <% else %>
      <%= button_to 'Join!', game_players_path(game) %>
    <% end %>
  <% when "playing" %>
    <% your_turn = game.current_player.user == current_user %>
    <% can_draw = your_turn && (game.plus > 0 || game.current_player.cards.all?{ !game.place?(it) }) %>
    <h2>
      <% if game.current_player.user == current_user %>
        Your turn!
      <% else %>
        <%= game.current_player.user.email %>'s turn
      <% end %>
    </h2>
    <div>
      <% if game.plus > 0 %>
        Stack: <%= game.plus %>
      <% end %>
    </div>
    <div>
      <% if game.dir.negative? %>
        Reversed!
      <% end %>
    </div>
    <div>
      <% if game.top.wild? %>
        Color: <%= game.color %>
      <% end %>
    </div>
    <div class="players-area">
      <div class="players-list">
        <% game.players.reject { it.user == current_user }.each do |player| %>
          <div class="player <%= 'current-player' if game.current_player == player %>">
            <div class="player-info">
              <strong><%= player.user.email %></strong>
              <% if game.current_player == player %>
                <span class="turn-indicator">Current Turn</span>
              <% end %>
              <% if player.cards.size == 1 && !player.runo? %>
                <%= button_to 'You didn\'t say rUNO!', game_turn_path(game, play: 'not_runo', player_id: player.id), class: 'runo-button' %>
              <% end %>
            </div>
            <ul class="other-player-cards" data-game-target="otherPlayerCards" data-player="<%= player.id %>">
              <% drawn = last_play[:player] == player && last_play[:play] == 'draw' %>
              <% player.cards.each.with_index do |card, index| %>
                <% draw = drawn && index >= player.cards.count - last_play[:draw] %>
                <li class="card other-player-card <%= draw ? 'drawn' : '' %>" data-game-target="otherCard" data-drawn="<%= draw.to_s %>">
                  <%= inline_svg("cards/back.svg") %>
                </li>
              <% end %>
            </ul>
            <% if last_play[:player] == player && last_play[:play].end_with?('runo') %>
              <div class="runo" data-game-target="runo">
                <% if last_play[:play] == 'runo' %>
                  rUNO!
                <% else %>
                  You didn't say rUNO!
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="play-area">
      <div class="discard">
        <div class="deck-stack" style="width: <%= (game.discard.length-1)*0.5 %>px"></div>
        <% played_card = last_play[:play] == 'card' && last_play[:player].user != current_user %>
        <div class="discard-card card card-<%= game.top.color %>" data-game-target="discard" data-player="<%= played_card ? last_play[:player].id : '' %>">
          <%= inline_card(game.top) %>
        </div>
      </div>
      <div class="deck">
        <div class="deck-stack" style="width: <%= (game.deck.length-1)*0.5 %>px"></div>
        <div class="card deck-next-card"><%= inline_svg("cards/back.svg") %></div>
        <div class="card deck-card <%= class_names(playable: can_draw) %>" data-game-target="deck">
          <% if can_draw %>
            <%= button_to game_turn_path(game, play: 'draw'), class: 'card-button', form: { class: 'card-form' }, data: { action: 'game#draw' } do %>
              <%= inline_svg("cards/back.svg") %>
            <% end %>
          <% else %>
            <%= inline_svg("cards/back.svg") %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="my-hand">
      <% if current_user_player.cards.count == 1 && !current_user_player.runo? %>
        <%= button_to 'rUNO!', game_turn_path(game, play: 'runo'), class: 'runo-button' %>
      <% end %>
      <ul class="cards" data-game-target="playerCards">
        <% current_user_player.cards.each do |card| %>
          <li data-controller="card" class="
            card
            card-<%= card.color %>
            <%= class_names(
              playable: your_turn && game.place?(card),
              unplayable: your_turn && !game.place?(card)
            ) %>
          ">
            <% if your_turn && game.place?(card) %>
              <% if card.wild? %>
                <button data-action="card#open" class="card-button">
                  <%= inline_card(card) %>
                </button>
                <dialog data-card-target="dialog">
                  <% Card::COLORS.each do |color| %>
                    <%= button_to color.capitalize, game_turn_path(game, play: 'card', card_id: card.id, color:, data: { action: 'game#play' }) %>
                  <% end %>
                </dialog>
              <% else %>
                <%= button_to game_turn_path(game, play: 'card', card_id: card.id), class: 'card-button', form: { class: 'card-form' }, data: { action: 'game#play' } do %>
                  <%= inline_card(card) %>
                <% end %>
              <% end %>
            <% else %>
              <%= inline_card(card) %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% when "finished" %>
    <h2><%= game.winner.email %> wins!</h2>
  <% when "abandoned" %>
    <h2>Abandoned!</h2>
  <% end %>

  <% if game.status.in?(%w[lobby playing]) && game.user == current_user %>
    <%= button_to "Abandon", game, method: :delete %>
  <% end %>
</div>

app/views/games/_lobby_game.html.erb
<li id="game_<%= game.id %>">
  <%= link_to game do %>
    #<%= game.id %> - <%= pluralize(game.players.length, 'player') %>
  <% end %>
</li>

app/views/games/show.html.erb
<%= turbo_stream_from "game_#{@game.id}_#{current_user.id}" %>

<%= render @game %>

<div>
  <%= link_to "Back to lobby", root_path %>
</div>